---
- name: demo playbook
  hosts: all
  gather_facts: yes
  tasks:
    - name: ping node
      ansible.builtin.ping:

    - name: make a tmpdir
      ansible.builtin.tempfile:
        state: directory
      register: tmpdir

    - name: touch 1000 files
      ansible.builtin.file:
        path: "{{ tmpdir.path }}/{{ 'dummyfile%05d' | format(item|int) }}"
        state: touch
      with_sequence: start=1 end=100

    - name: remove the 1000 files that you just created
      ansible.builtin.file:
        path: "{{ tmpdir.path }}/{{ 'dummyfile%05d' | format(item|int) }}"
        state: absent
      with_sequence: start=1 end=100

    - name: remove the tmpdir
      ansible.builtin.file:
        path: "{{ tmpdir.path }}"
        state: absent
      when: tmpdir.path is defined

    - name: show this node's facts
      ansible.builtin.debug:
        var: ansible_facts
