---
- name: show exposed file test
  hosts: localhost
  
  tasks:
    - name: make a temporary directory
      ansible.builtin.command: mktemp
      register: mktemp

    - name: test kinit
      ansible.builtin.shell: echo '"{{ krb_password }}"' | kinit '"{{ krb_user }}"'
      environment:
        KRB5CCNAME: "{{ mktemp.stdout_lines[0] }}"
      register: result

    - ansible.builtin.debug:
        msg: "{{ result.stdout }}"
